# Generated by Django 2.2.1 on 2019-05-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('icon', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=250)),
                ('date', models.IntegerField()),
                ('belongs_to', models.ForeignKey(null=True, on_delete='SET_NULL', related_name='question', to='questions.job')),
            ],
        ),
    ]
