# Generated by Django 2.2.1 on 2019-05-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190512_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', related_name='question', to='questions.Job'),
        ),
    ]
