# Generated by Django 2.2.1 on 2019-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190514_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short',
            field=models.CharField(default='fillme', max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', related_name='question', to='questions.Job'),
        ),
    ]
